language: node_js
node_js:
  - lts/boron
  - lts/carbon
  - lts/dubnium
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage --maxWorkers=4
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
