language: node_js
node_js:
  - lts/boron
  - lts/carbon
  - lts/dubnium
  - stable
cache: npm
script:
  - npm test -- --coverage --runInBand
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
