language: node_js
node_js:
  - lts/argon
  - lts/boron
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test -- --coverage --no-cache --runInBand
after_success:
  - yarn global add coveralls
  - cat coverage/lcov.info | coveralls
