language: node_js
node_js:
  - lts/argon
  - lts/boron
  - stable
script:
  - npm test -- --coverage --no-cache --runInBand
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
