language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage --no-cache --runInBand
after_success:
  - npm install -g coveralls
  - cat coverage/remapped/lcov.info | coveralls
